// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
#[derive(Queryable, Debug)]
pub struct IdentitasPengaju {
    pub id: String,
    pub kontak: String,
    pub pengaju_id: String,
}

#[derive(Queryable, Debug)]
pub struct Kompetisi {
    pub id: String,
    pub nama_pendaftar: String,
    pub nim_pendaftar: String,
    pub email_pendaftar: String,
    pub nama_lembaga_pendaftar: String,
    pub nama_kompetisi: String,
    pub kategori_kompetisi: String,
    pub deskripsi_kompetisi: String,
    pub tags_kompetisi: String,
    pub tanggal_pelaksanaan: NaiveDateTime,
    pub batas_registrasi: NaiveDateTime,
    pub link_registrasi: String,
    pub link_webiste: String,
    pub link_linkedin: String,
    pub akun_instagram: String,
    pub id_line: String,
    pub akun_twitter: String,
    pub link_poster: String,
}

#[derive(Queryable, Debug)]
pub struct KriteriaAnggota {
    pub id: String,
    pub kompetisi_id: String,
    pub role: String,
    pub deskripsi_kriteria: String,
}

#[derive(Queryable, Debug)]
pub struct TimBuddy {
    pub id: String,
    pub kompetisi_id: String,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: String,
    pub email: String,
    pub name: String,
    pub nim: String,
    pub password: String,
    pub role: /* TODO: unknown type Role */,
}

#[derive(Queryable, Debug)]
pub struct Verification {
    pub id: String,
    pub email: String,
    pub name: String,
    pub status: /* TODO: unknown type VerificationStatus */,
}

