// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
#[derive(Queryable, Debug)]
pub struct IdentitasPengaju {
    pub id: String,
    pub kontak: String,
    pub pengaju_id: String,
}

#[derive(Queryable, Debug)]
pub struct Kompetisi {
    pub id: String,
    pub nama_lembaga_pendaftar: String,
    pub no_telp: String,
    pub nama_kompetisi: String,
    pub kategori_kompetisi: String,
    pub deskripsi_kompetisi: String,
    pub tags_kompetisi: String,
    pub tanggal_pelaksanaan: NaiveDateTime,
    pub batas_awal_registrasi: NaiveDateTime,
    pub batas_akhir_registrasi: NaiveDateTime,
    pub link_registrasi: String,
    pub link_website: String,
    pub link_linkedin: String,
    pub akun_instagram: String,
    pub id_line: String,
    pub akun_twitter: String,
    pub link_poster: String,
    pub status: String,
    pub user_id: String,
}

#[derive(Queryable, Debug)]
pub struct KriteriaAnggota {
    pub id: String,
    pub kompetisi_id: String,
    pub role: String,
    pub deskripsi_kriteria: String,
}

#[derive(Queryable, Debug)]
pub struct TimBuddy {
    pub id: String,
    pub kompetisi_id: String,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: String,
    pub email: String,
    pub name: String,
    pub password: String,
    pub is_admin: bool,
    pub is_active: bool,
}

#[derive(Queryable, Debug)]
pub struct Verification {
    pub id: String,
    pub user_id: String,
}

